### PR TITLE
Updated Vite support

### LINKED ISSUE #1: Add Vite Support
Firstly, just wanted to say thanks for creating this project - it's exactly what I was looking for.

I am using Vite in my app and was wondering if you'd be open to adding vite support?

I'd be happy to help in the implementation.

### PR DESCRIPTION
**Pull request by bildungsroman**
Adds support for Vite, closes #1 and #14 .

This builds off of @GregVGW's excellent long-open [PR](https://github.com/pixijs/storybook/pull/14) and updates libraries for Pixi 8 and Storybook 8 as well as adding Vite support to the README.

### CODE REVIEW

**Comment by bildungsroman** [comment]
> Hey @bildungsroman thanks for putting this together! I'll try and get round to reviewing this next week

Thanlks @Zyie, this is pretty urgent for my team so I would definitely appreciate a quick review!

**Comment by Zyie** [comment]
Hey @bildungsroman thanks for all the hard work on this PR. I am going to close this in favor of #22 as the storybook v8 part of this PR was not fully implemented.

I've released `1.0.0-alpha.0` for you to test out

**Comment by bildungsroman** [comment]
Awesome, thanks so much! I'll import alpha today and try it out

**Comment by bildungsroman** [comment]
LGTM! Please let me know when it's merged so I can import it properly into my package

**Pull request closed without merging**
