### PR TITLE
breaking: storybook v8 and vite support

### LINKED ISSUE #1: Add Vite Support
Firstly, just wanted to say thanks for creating this project - it's exactly what I was looking for.

I am using Vite in my app and was wondering if you'd be open to adding vite support?

I'd be happy to help in the implementation.

### LINKED ISSUE #18: Update function is not bound to the storyObject
[`this.view`](https://github.com/pixijs/storybook/blob/d3e16da2eba686bca6aac21dff018806aa33024f/packages/example-v8/stories/BunnyDemo.js#L33) is undefined in bunny example, running with latest `pixi/storybook`. [`this`](https://github.com/pixijs/storybook/blob/d3e16da2eba686bca6aac21dff018806aa33024f/packages/storybook-renderer/src/render.ts#L33-L46) is the arrow function instead of the story object, so `this.view.rotation` fails with undefined reference.

### LINKED ISSUE #20: Storybook 8 support
https://github.com/storybookjs/storybook/issues/26031

### PR DESCRIPTION
**Pull request by Zyie**
closes #1, #18, and #20

Huge thanks to @bildungsroman and @GregVGW for the help with adding the vite support

### CODE REVIEW

**Comment by bildungsroman** [comment]
This looks great, worked for me!

**Comment by bildungsroman** [comment]
Hey @Zyie, when do you expect to merge this in?

**Comment by Zyie** [comment]
> Hey @Zyie, when do you expect to merge this in?

merged and released!

**Comment by bildungsroman** [comment]
Yay, thanks so much!!

**Pull request merged**
